src/wordplease/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.routers import DefaultRouter

from tasks.api import TaskViewSet, BlogsViewSet
from tasks.views import post_list, post_detalle, mis_post, NewPost, home, View
from user.api import UserViewSet

from user.views import LoginView, logout, RegistroUsuario

router = DefaultRouter()
router.register("user", UserViewSet, base_name="user_api")
router.register("tasks", TaskViewSet)
router.register("blogs", BlogsViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name='home'),
    url(r'^blogs$', post_list, name='post_list'),
    url(r'^signup$', RegistroUsuario.as_view(), name='RegistroUsuario'),
    url(r'^blogs/(?P<user>[-\w]+)/$', mis_post, name='mis_post'),
    url(r'^new-post$', NewPost.as_view(), name='new_post'),
    url(r'^blogs/(?P<user>[-\w]+)/(?P<post_pk>[0-9]+)$', post_detalle, name='post_detalle'),
    url(r'^login$', LoginView.as_view(), name='login'),
    url(r'^logout$', logout, name='logout'),

    url(r'^blogs/(?P<user>[-\w]+)/(?P<post_pk>[0-9]+)/comment/$', View.add_comment_to_post, name='add_comment_to_post'),

# API Users & Tasks
    url(r'^api/1.0/', include(router.urls)),



]

src/tasks/models.py
from django.contrib.auth.models import User
from django.db import models

from django.conf import settings


class Categorias(models.Model):

    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Post(models.Model):

    PUBLICO = 'PUB'
    PRIVADO = 'PRI'
    Estado = (
        (PUBLICO, 'Publico'),
        (PRIVADO, 'Privado')
    )


    categoria = models.ManyToManyField(Categorias)
    titulo = models.CharField(max_length=100)
    intro = models.TextField()
    descripcion = models.TextField()
    imagen = models.URLField()
    user = models.ForeignKey(User, related_name='user_post')
    deadline = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    estado = models.CharField(max_length=3, default=PUBLICO, choices=Estado)


    def __str__(self):
        return self.titulo


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

src/user/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

src/tasks/views.py
from datetime import date

from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import View


from tasks.form import PostForm, CommentForm
from tasks.models import Post, Categorias

def home(request):

    # recupera todas las tareas
    post = Post.objects.order_by('-created_at').all()




    #crea la representacion de los datos
    context ={
        'post_objects': post,

    }

    #responder
    return render(request, 'tasks/home.html', context)

def post_list(request):

    # recupera todas las tareas
    #publico = Post.Estado.objects.get(estado='publico')
    if not request.user.is_authenticated:
        post = Post.objects.filter(estado='PUB').order_by('-created_at')

    else:
        post = Post.objects.order_by('-created_at').all()



    #crea la representacion de los datos
    context ={
        'post_objects': post,

    }

    #responder
    return render(request, 'tasks/blogs.html', context)

@login_required()
def mis_post(request, user):

    # recupera todas las tareas
    try:
        u = User.objects.get(username=user).id
        post = Post.objects.filter(user=u).order_by('-created_at')
    except Post.DoesNotExist:
        return render(request, '404.html', {}, status=404)
    except Post.MultipleObjectsReturned:
        return HttpResponse('existen varias tareas con ese identificador', status=300)


    #crea la representacion de los datos
    context ={
        'mi_post': post
    }

    #responder
    return render(request, 'tasks/mi_post.html', context)

@login_required()
def post_detalle(request, user, post_pk):

    try:
        u = User.objects.get(username=user).id
        post = Post.objects.filter(user=u).select_related().get(pk=post_pk)

    except Post.DoesNotExist:
        return render(request, '404.html', {}, status=404)
    except Post.MultipleObjectsReturned:
        return HttpResponse('existen varias tareas con ese identificador', status=300)
    context = {
        'post': post
    }
    return render(request, 'tasks/detalle.html', context)


class NewPost(View):

    def get(self, request):
        form = PostForm()

        context = {
            'form': form
        }
        return render(request, 'tasks/new.html', context)


    def post(self, request):

        post_user = Post(user=request.user)
        form =PostForm(request.POST, instance=post_user)

        if form.is_valid():

            new = form.save()

            mensaje = 'tarea creada '
            form = PostForm()
        else:
            mensaje ='se ha producido un  error'

        context = {

            'form': form,
            'mensaje':mensaje
        }

        return render(request, 'tasks/new.html', context)


class View(View):
    def add_comment_to_post(request, user, post_pk):
        post = render(request, '404.html', {}, status=404)
        if request.method == "POST":
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save()
                comment.post =  post
                comment.save()
                return redirect('detalle', user, pk=post.pk)
        else:
            form = CommentForm()
        return render(request, 'tasks/add_comment_to_post.html', {'form': form})

src/user/views.py
from django.contrib.auth import authenticate, login as django_login, logout as django_logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView

from tasks.registro import RegistroForm
from user.forms import LoginForm


class LoginView(View):

    def get(selft, request):

        context = {
        'form': LoginForm()
        }

        return render(request, 'login.html', context)

    def post(selft, request):
        form = LoginForm(request.POST)
        context = dict()
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                #usuario autenticado
                django_login(request,user)
                url = request.GET.get('next', 'new_post')
                return  redirect(url)
            else:
                #usuario no autenticado
                context['error'] = 'error username o password'
            context['form'] = form
        return render(request, 'login.html', context)

def logout(request):
    django_logout(request)
    return redirect('login')

class RegistroUsuario(CreateView):
    model = User
    template_name = 'tasks/registro.html'
    form_class = RegistroForm
    success_url = reverse_lazy('new_post')

src/ui/templates/basico.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Wordplease {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
</head>
<body>
    <h1>
        Wordplease
    </h1>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'home' %}" title="home">Home</a></li>

                <li><a class="navbar-brand" href="{% url 'post_list' %}" title="blogs">Blogs</a></li>

                <li><a class="navbar-brand" href="{% url 'RegistroUsuario' %}" title="registro">Registro</a></li>

            {% if user.is_authenticated %}

                <li><a class="navbar-brand" href="{% url 'logout' %}" title="logout">logout</a></li>

                <li> <a class="navbar-brand" href="{% url 'mis_post' user %}" title="Login">Mis post</a></li>

                <li><a class="navbar-brand" href="{% url 'new_post' %}" title="new">New post</a></li>

            {% else %}

                <li><a class="navbar-brand" href="{% url 'login' %}" title="Login">Login</a></li>

            </ul>
        </div>
    </nav>


    {% endif %}
    <hr>
{% block content %}{% endblock %}

</body>
</html>

src/ui/templates/login.html
{% extends 'basico.html' %}

{% block content %}

<h2>Login</h2>

<div style="color:red">{{ error }}</div>

<form method="post">
                {% csrf_token %}
                {{form.as_p}}
    <div>
        <button>login</button>
    </div>

</form>

{% endblock %}

src/ui/templates/tasks/add_comment_to_post.html
{% extends 'basico.html' %}

{% block title %}{{post.titulo}}{% endblock %}

{% block content %}

    <h1>New comment</h1>
    <form method="post" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

src/ui/templates/tasks/blogs.html
{% extends 'basico.html' %}

{% block content %}
<tbody>

    {% for post in post_objects %}
    <p>
        {% if user.is_authenticated %}
        <a  href="{% url 'post_detalle' user post.pk %}" title="view {{ post.titulo }}">
            {{post.titulo}}
        </a>
        <p>{{post.user}}</p>
        {% else %}
        <p style="color:red">no estas autenticado</p>
        {% endif %}

            <p>{{post.intro}}</p>
            <p><img src="{{ post.imagen }}" /></p>
            <p>{{post.get_estado_display}}</p>


    {% endfor %}
    </p>
</tbody>
{% endblock %}

src/ui/templates/tasks/detalle.html
{% extends 'basico.html' %}

{% block title %}{{post.titulo}}{% endblock %}

{% block content %}

    <p>{{cat.nombre}}</p>
    <p>{{ post.categoria.all|join:", " }}</p>
    <p>{{post.titulo}}</p>
    <p>{{post.intro}}</p>
    <p>{{post.descripcion}}</p>
    <p><img src="{{ post.imagen }}" /></p>
    <p>{{post.deadline}}</p>
    <p>{{post.created_at}}</p>

<h2>Deja un comentario</h2>
<a class="btn btn-default" href="{% url 'add_comment_to_post' user post.pk %}">Add comment</a>
<h1>New comment</h1>
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
<hr>
<h2>Comentarios</h2>
{% for comment in post.comments.all %}
    <div class="comment">
        <div class="date">{{ comment.created_date }}</div>
        <strong>{{ comment.author }}</strong>
        <p>{{ comment.text|linebreaks }}</p>
    </div>
{% empty %}
    <p>No comments here yet :(</p>

{% endfor %}
{% endblock %}

src/ui/templates/tasks/home.html
{% extends 'basico.html' %}
{% block title %} Home {% endblock %}
{% block content %}

<h2>Bienvenidos</h2>

{% endblock %}

src/ui/templates/tasks/mi_post.html
{% extends 'basico.html' %}

{% block content %}
<tbody>

{% for post in mi_post %}

    <p>
        <a  href="{% url 'post_detalle' user post.pk %}" title="view {{ post.titulo }}">
            {{post.titulo}}
        </a>
            <p>{{ post.categoria.all|join:", " }}</p>
            <p>{{post.intro}}</p>
            <p><img src="{{ post.imagen }}" /></p>
            <p>{{post.get_user_display}}</p>
            <p>{{post.created_at}}</p>

    {% endfor %}
    </p>
</tbody>
{% endblock %}

src/ui/templates/tasks/new.html
{% extends 'basico.html' %}
{% block title %} New post {% endblock %}
{% block content %}
<h2>new post</h2>

{% autoescape off %}
    <div>{{ mensaje }}</div>
{% endautoescape %}


<form method="post" novalidate>
    {% csrf_token %}
    {{form.as_p}}
    <div>
        <button>submit</button>
    </div>



</form>

{% endblock %}

src/ui/templates/tasks/registro.html
{% extends 'basico.html' %}
{% block title %} Registro {% endblock %}
{% block content %}
<h2>Registro</h2>

<form method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <div>
        <button>submit</button>
    </div>

</form>

{% endblock %}